version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carpark_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carpark_network

  app:
    build: .
    container_name: carpark_app
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8090
    networks:
      - carpark_network

volumes:
  postgres_data:

networks:
  carpark_network:
    driver: bridge